apiVersion: v1
kind: Service
metadata:
  name: my-service
  #annotations:
    #harness.io/primary-service: "true"
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: web
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  #annotations:
    #harness.io/stage-service: "true"
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: web
