apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
spec:
  selector:
    matchLabels:
      app: web
  replicas: {{.Values.replicas}}
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: uruku/webapp
        ports:
        - containerPort: 5000
